In [1]:
# 读写NDArrays
# 直接使用save 和 load函数分别存储和读取NDArray
from mxnet import nd
from mxnet.gluon import nn

In [2]:
x = nd.ones(3)

In [3]:
nd.save('x', x)

In [4]:
x2 = nd.load('x')

In [5]:
x2

[
 [ 1.  1.  1.]
 <NDArray 3 @cpu(0)>]

In [6]:
# 存储一列NDArray 并读回内存
y = nd.zeros(4)
nd.save('xy', [x, y])
x2, y2 = nd.load('xy')
(x2, y2)

(
 [ 1.  1.  1.]
 <NDArray 3 @cpu(0)>, 
 [ 0.  0.  0.  0.]
 <NDArray 4 @cpu(0)>)

In [7]:
# 存储并读取一个从字符串映射到NDArray
mydict = {'x': x, 'y': y}
nd.save('mydict', mydict)
mydict2 = nd.load('mydict')
mydict2

{'x': 
 [ 1.  1.  1.]
 <NDArray 3 @cpu(0)>, 'y': 
 [ 0.  0.  0.  0.]
 <NDArray 4 @cpu(0)>}

In [10]:
# 读写Gluon模型的参数
class MLP(nn.Block):
    def __init__(self, **kwargs):
        super(MLP, self).__init__(**kwargs)
        self.hidden = nn.Dense(256, activation='relu')
        self.output = nn.Dense(10)
    
    def forward(self, x):
        return self.output(self.hidden(x))

In [11]:
net = MLP()
net.initialize()
x = nd.random.uniform(shape=(2, 20))
y = net(x)

In [12]:
filename = 'mlp.params'
net.save_parameters(filename)

In [13]:
net2 = MLP()
net2.load_parameters(filename)

In [14]:
y2 = net2(x)
y2 == y


[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]
<NDArray 2x10 @cpu(0)>